# This cloudbuild.yaml config file is triggered in two contexts:
#
#
# Trigger #1:
#
# marketplace-k8s-app-tools push to any branch
# https://console.cloud.google.com/cloud-build/triggers/0762301f-81af-4c60-8d12-a4cbdf8d6ea1?project=marketplace-k8s-app-tools
#
# This build trigger asserts the invariant that the source code can
# be built and pushed into a repository. Its success blocks pull
# request. gcr.io/marketplace-k8s-app-tools read access restricted.
#
#
# Trigger #2:
#
# cloud-marketplace-tools push to master branch
# https://console.cloud.google.com/cloud-build/triggers/0257675b-9860-40a0-90c3-640a196e6a56?project=cloud-marketplace-tools
#
# This build trigger asserts the invariant that each commit on the master
# branch of GoogleCloudPlatform/marketplace-k8s-app-tools will be built
# and tagged in gcr.io/cloud-marketplace-tools/master.
steps:

- id: Build dev
  name: gcr.io/cloud-builders/docker
  waitFor:
  - '-'
  args:
  - build
  - --tag
  - gcr.io/$PROJECT_ID/$BRANCH_NAME/dev:sha_$COMMIT_SHA
  - --tag
  - gcr.io/$PROJECT_ID/$BRANCH_NAME/dev:sha_$SHORT_SHA
  - --file
  - marketplace/dev/Dockerfile
  - .

- id: Build deployer_envsubst
  name: gcr.io/cloud-builders/docker
  waitFor:
  - '-'
  args:
  - build
  - --tag
  - gcr.io/$PROJECT_ID/$BRANCH_NAME/deployer_envsubst:sha_$COMMIT_SHA
  - --tag
  - gcr.io/$PROJECT_ID/$BRANCH_NAME/deployer_envsubst:sha_$SHORT_SHA
  - --file
  - marketplace/deployer_envsubst_base/Dockerfile
  - .

- id: Build deployer_helm
  name: gcr.io/cloud-builders/docker
  waitFor:
  - '-'
  args:
  - build
  - --tag
  - gcr.io/$PROJECT_ID/$BRANCH_NAME/deployer_helm:sha_$COMMIT_SHA
  - --tag
  - gcr.io/$PROJECT_ID/$BRANCH_NAME/deployer_helm:sha_$SHORT_SHA
  - --file
  - marketplace/deployer_helm_base/Dockerfile
  - .

images:
  - gcr.io/$PROJECT_ID/$BRANCH_NAME/dev:sha_$COMMIT_SHA
  - gcr.io/$PROJECT_ID/$BRANCH_NAME/dev:sha_$SHORT_SHA
  - gcr.io/$PROJECT_ID/$BRANCH_NAME/deployer_envsubst:sha_$COMMIT_SHA
  - gcr.io/$PROJECT_ID/$BRANCH_NAME/deployer_envsubst:sha_$SHORT_SHA
  - gcr.io/$PROJECT_ID/$BRANCH_NAME/deployer_helm:sha_$COMMIT_SHA
  - gcr.io/$PROJECT_ID/$BRANCH_NAME/deployer_helm:sha_$SHORT_SHA
