steps:

- id: &PublishImages Publish Images
  name: gcr.io/cloud-builders/docker
  waitFor:
  - '-'
  entrypoint: bash
  args:
  - -exc
  - |
    docker pull gcr.io/marketplace-k8s-app-tools/k8s/dev:sha_$COMMIT_SHA
    docker tag gcr.io/marketplace-k8s-app-tools/k8s/dev:sha_$COMMIT_SHA gcr.io/$PROJECT_ID/k8s/dev:$TAG_NAME

    docker pull gcr.io/marketplace-k8s-app-tools/k8s/deployer_helm:sha_$COMMIT_SHA
    docker tag gcr.io/marketplace-k8s-app-tools/k8s/deployer_helm:sha_$COMMIT_SHA gcr.io/$PROJECT_ID/k8s/deployer_helm:$TAG_NAME

    docker pull gcr.io/marketplace-k8s-app-tools/k8s/deployer_helm/onbuild:sha_$COMMIT_SHA
    docker tag gcr.io/marketplace-k8s-app-tools/k8s/deployer_helm/onbuild:sha_$COMMIT_SHA gcr.io/$PROJECT_ID/k8s/deployer_helm/onbuild:$TAG_NAME

    docker pull gcr.io/marketplace-k8s-app-tools/k8s/deployer_helm_tiller:sha_$COMMIT_SHA
    docker tag gcr.io/marketplace-k8s-app-tools/k8s/deployer_helm_tiller:sha_$COMMIT_SHA gcr.io/$PROJECT_ID/k8s/deployer_helm_tiller:$TAG_NAME

    docker pull gcr.io/marketplace-k8s-app-tools/k8s/deployer_helm_tiller/onbuild:sha_$COMMIT_SHA
    docker tag gcr.io/marketplace-k8s-app-tools/k8s/deployer_helm_tiller/onbuild:sha_$COMMIT_SHA gcr.io/$PROJECT_ID/k8s/deployer_helm_tiller/onbuild:$TAG_NAME

    docker pull gcr.io/marketplace-k8s-app-tools/k8s/deployer_envsubst:sha_$COMMIT_SHA
    docker tag gcr.io/marketplace-k8s-app-tools/k8s/deployer_envsubst:sha_$COMMIT_SHA gcr.io/$PROJECT_ID/k8s/deployer_envsubst:$TAG_NAME

- id: Publish Charts
  name: gcr.io/$PROJECT_ID/k8s/dev:$TAG_NAME
  waitFor:
  - *PublishImages
  entrypoint: bash
  args:
  - -exc
  - |
    mkdir charts-tgz/
    helm init --client-only
    helm package marketplace/charts/marketplace-integration/ \
        --version $TAG_NAME \
        --destination charts-tgz/
    #TODO(trironkk): Update index.yaml.

images:
- gcr.io/$PROJECT_ID/k8s/dev:$TAG_NAME
- gcr.io/$PROJECT_ID/k8s/deployer_helm:$TAG_NAME
- gcr.io/$PROJECT_ID/k8s/deployer_helm/onbuild:$TAG_NAME
- gcr.io/$PROJECT_ID/k8s/deployer_helm_tiller:$TAG_NAME
- gcr.io/$PROJECT_ID/k8s/deployer_helm_tiller/onbuild:$TAG_NAME
- gcr.io/$PROJECT_ID/k8s/deployer_envsubst:$TAG_NAME

artifacts:
  objects:
    location: gs://$PROJECT_ID/charts/
    paths:
    - charts-tgz/*
