#!/bin/bash

set -eox pipefail

test_directory=$(mktemp --dry-run)
cp -r $(dirname "$0") "$test_directory"
cd "$test_directory"

image="$REGISTRY/testing/deployer_helm_tiller_base/1:$MARKETPLACE_TOOLS_TAG-$TEST_ID"

docker build \
    --build-arg "REGISTRY=$REGISTRY" \
    --build-arg "MARKETPLACE_TOOLS_TAG=$MARKETPLACE_TOOLS_TAG" \
    --build-arg "HELM_DEPENDENCY_BUILD=true" \
    --tag "$image" \
    .

docker push "$image"

docker run \
    "$REGISTRY/k8s/dev:$MARKETPLACE_TOOLS_TAG" \
    cat /scripts/dev \
  > dev
chmod a+x dev

export MARKETPLACE_TOOLS_IMAGE="$REGISTRY/k8s/dev"

app_parameters="{\"marketplace-integration.image\": \"$image\"}"
./dev \
  /scripts/verify \
      --deployer="$image" \
      --parameters="$app_parameters"
