FROM python:3

# RUN apt-get update \
#     && apt-get install -y --no-install-recommends \
#         python3-pip \
#         python3-setuptools \
#     && rm -rf /var/lib/apt/lists/*

RUN pip3 install \
      futures \
      google-cloud-storage \
      pyflakes \
      pyOpenSSL \
      pyyaml \
      wheel \
      yapf

