#!/usr/bin/env python3
# Copyright 2018 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import datetime
import json
import sys
import yaml


def _fallback_serializer(obj):
  """JSON serializer for objects not serializable by default json code"""
  if isinstance(obj, (datetime.datetime, datetime.date)):
    return obj.isoformat()
  raise TypeError("Type %s not serializable" % type(obj))


content = sys.stdin.read()
for loaded in yaml.safe_load_all(content):
  print(json.dumps(loaded, default=_fallback_serializer))
