#!/usr/bin/env python
#
# Copyright 2018 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import sys
import yaml
import json

from subprocess import Popen, PIPE, STDOUT

json2yaml = ["json2yaml", "toyaml"]
yaml2json = ["yaml2json", "tojson"]

opt = sys.argv[1]
content = sys.stdin.read()
if opt in yaml2json:
  split_content = content.split("---\n")
  if len(split_content) == 1:
    loaded = yaml.load(content)
    print(json.dumps(loaded))
  else:
    for part in split_content:
      print(json.dumps(yaml.load(part)))
if opt in json2yaml:
  loaded = json.load(content)
  print(yaml.dump(loaded))
