#!/bin/bash

set -eox pipefail

test_name="$(dirname "$0" | cut -d/ -f2-)"
test_directory=$(mktemp --dry-run)
cp -r $(dirname "$0") "$test_directory"
cd "$test_directory"

export REGISTRY="$REGISTRY/$test_name"
export TAG="$MARKETPLACE_TOOLS_TAG-$TEST_ID"

# Runs diagnostic tool to make sure your environment is properly setup.
make app/doctor

make app/verify
