# This cloudbuild.yaml config file is triggered when pull requests are
# merged into the master branch, and ensures that each commit on the
# master branch has build artifacts associated with it.
#
# Associated build trigger:
# http://console.cloud.google.com/cloud-build/triggers/0762301f-81af-4c60-8d12-a4cbdf8d6ea1

steps:

- id: Build dev
  name: gcr.io/cloud-builders/docker
  waitFor:
  - '-'
  args:
  - build
  - --tag
  - gcr.io/$PROJECT_ID/$BRANCH_NAME/dev:sha_$COMMIT_SHA
  - --tag
  - gcr.io/$PROJECT_ID/$BRANCH_NAME/dev:sha_$SHORT_SHA
  - --file
  - marketplace/dev/Dockerfile
  - .

- id: Build deployer_envsubst
  name: gcr.io/cloud-builders/docker
  waitFor:
  - '-'
  args:
  - build
  - --tag
  - gcr.io/$PROJECT_ID/$BRANCH_NAME/deployer_envsubst:sha_$COMMIT_SHA
  - --tag
  - gcr.io/$PROJECT_ID/$BRANCH_NAME/deployer_envsubst:sha_$SHORT_SHA
  - --file
  - marketplace/deployer_envsubst_base/Dockerfile
  - .

- id: Build deployer_helm
  name: gcr.io/cloud-builders/docker
  waitFor:
  - '-'
  args:
  - build
  - --tag
  - gcr.io/$PROJECT_ID/$BRANCH_NAME/deployer_helm:sha_$COMMIT_SHA
  - --tag
  - gcr.io/$PROJECT_ID/$BRANCH_NAME/deployer_helm:sha_$SHORT_SHA
  - --file
  - marketplace/deployer_helm_base/Dockerfile
  - .

images:
  - gcr.io/$PROJECT_ID/$BRANCH_NAME/dev:sha_$COMMIT_SHA
  - gcr.io/$PROJECT_ID/$BRANCH_NAME/dev:sha_$SHORT_SHA
  - gcr.io/$PROJECT_ID/$BRANCH_NAME/deployer_envsubst:sha_$COMMIT_SHA
  - gcr.io/$PROJECT_ID/$BRANCH_NAME/deployer_envsubst:sha_$SHORT_SHA
  - gcr.io/$PROJECT_ID/$BRANCH_NAME/deployer_helm:sha_$COMMIT_SHA
  - gcr.io/$PROJECT_ID/$BRANCH_NAME/deployer_helm:sha_$SHORT_SHA
