# This cloudbuild.yaml config file is triggered when pull requests are
# merged into the master branch, and ensures that each commit on the
# master branch has build artifacts associated with it.
#
# Associated build trigger:
# http://console.cloud.google.com/cloud-build/triggers/0762301f-81af-4c60-8d12-a4cbdf8d6ea1

steps:

- id: Build dev
  name: gcr.io/cloud-builders/docker
  waitFor:
  - '-'
  args:
  - build
  - --tag
  - gcr.io/$PROJECT_ID/$BRANCH_NAME/dev
  - --tag
  - gcr.io/$PROJECT_ID/$BRANCH_NAME/dev:$COMMIT_SHA
  - --tag
  - gcr.io/$PROJECT_ID/$BRANCH_NAME/dev:$SHORT_SHA
  - --file
  - marketplace/dev/Dockerfile
  - .

- id: Build deployer_envsubst
  name: gcr.io/cloud-builders/docker
  waitFor:
  - '-'
  args:
  - build
  - --tag
  - gcr.io/$PROJECT_ID/$BRANCH_NAME/deployer_envsubst
  - --tag
  - gcr.io/$PROJECT_ID/$BRANCH_NAME/deployer_envsubst:$COMMIT_SHA
  - --tag
  - gcr.io/$PROJECT_ID/$BRANCH_NAME/deployer_envsubst:$SHORT_SHA
  - --file
  - marketplace/deployer_envsubst_base/Dockerfile
  - .

- id: Build deployer_helm
  name: gcr.io/cloud-builders/docker
  waitFor:
  - '-'
  args:
  - build
  - --tag
  - gcr.io/$PROJECT_ID/$BRANCH_NAME/deployer_helm
  - --tag
  - gcr.io/$PROJECT_ID/$BRANCH_NAME/deployer_helm:$COMMIT_SHA
  - --tag
  - gcr.io/$PROJECT_ID/$BRANCH_NAME/deployer_helm:$SHORT_SHA
  - --file
  - marketplace/deployer_helm_base/Dockerfile
  - .

images:
  - gcr.io/$PROJECT_ID/$BRANCH_NAME/dev
  - gcr.io/$PROJECT_ID/$BRANCH_NAME/dev:$COMMIT_SHA
  - gcr.io/$PROJECT_ID/$BRANCH_NAME/dev:$SHORT_SHA
  - gcr.io/$PROJECT_ID/$BRANCH_NAME/deployer_envsubst
  - gcr.io/$PROJECT_ID/$BRANCH_NAME/deployer_envsubst:$COMMIT_SHA
  - gcr.io/$PROJECT_ID/$BRANCH_NAME/deployer_envsubst:$SHORT_SHA
  - gcr.io/$PROJECT_ID/$BRANCH_NAME/deployer_helm
  - gcr.io/$PROJECT_ID/$BRANCH_NAME/deployer_helm:$COMMIT_SHA
  - gcr.io/$PROJECT_ID/$BRANCH_NAME/deployer_helm:$SHORT_SHA
