#!/bin/bash
#
# Copyright 2018 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -eo pipefail

for i in "$@"
do
case $i in
  --deployer=*)
    deployer="${i#*=}"
    shift
    ;;
  --parameters=*)
    parameters="${i#*=}"
    shift
    ;;
  --wait_timeout=*)
    wait_timeout="${i#*=}"
    shift
    ;;
  *)
    echo "Unrecognized flag: $i"
    exit 1
    ;;
esac
done

[[ -z "$deployer" ]] && deployer="$APP_DEPLOYER_IMAGE"
[[ -z "$parameters" ]] && parameters="{}"
[[ -z "$wait_timeout" ]] && wait_timeout=600

# Extract schema and values files.
docker run \
    --entrypoint=/bin/bash \
    --rm "${deployer}" \
    -c 'cat /data/schema.yaml' \
> /data/schema.yaml
echo "$parameters" \
  | json2yaml \
> /data/values.yaml

# Compose test id.
test_id="$(cat /dev/urandom \
    | tr -dc 'a-z0-9' \
    | head -c 8 \
|| true)"

# Extract keys for name and namespace.
name_key="$(extract_schema_key.py \
    --schema_file=/data/schema.yaml \
    --type NAME)"
namespace_key="$(extract_schema_key.py \
    --schema_file=/data/schema.yaml \
    --type NAMESPACE)"

export NAME="apptest-$test_id"
export NAMESPACE="apptest-$test_id"

# Stitch in name and namespace parameters.
parameters=$(echo "$parameters" \
  | jq \
    --arg name_key "$name_key" \
    --arg name "$NAME" \
    --arg namespace_key "$namespace_key" \
    --arg namespace "$NAMESPACE" \
    '.[$name_key] = $name | .[$namespace_key] = $namespace')

echo "INFO Parameters: $parameters"

echo "INFO Creates namespace \"$NAMESPACE\""
kubectl create namespace "$NAMESPACE"

function delete_namespace() {
  echo "INFO Collecting events for namespace \"$NAMESPACE\""
  kubectl get events --namespace="$NAMESPACE" || echo "ERROR Failed to get events for namespace \"$NAMESPACE\""

  if [[ ! -z $deployer_name ]]; then
    echo "INFO Collecting logs for deployer"
    kubectl logs "jobs/$deployer_name" --namespace="$NAMESPACE" || echo "ERROR Failed to get logs for deployer $deployer_name"
  fi

  echo "INFO Deleting namespace \"$NAMESPACE\""
  kubectl get all --namespace "$NAMESPACE" --output=yaml
  kubectl delete namespace "$NAMESPACE"
}

function clean_and_exit() {
  message=$1
  [[ -z "$message" ]] || echo "$message"

  delete_namespace
  exit 1
}

echo "INFO Initializes the deployer container which will deploy all the application components"
/scripts/install \
  --deployer="$deployer" \
  --parameters="$parameters" \
  --entrypoint='/bin/deploy_with_tests.sh' \
  || clean_and_exit "ERROR Failed to start deployer"

echo "INFO wait for the deployer to succeed"
deployer_name="${NAME}-deployer"

start_time=$(date +%s)
poll_interval=4
while true; do
  deployer_status=$(kubectl get "jobs/$deployer_name" --namespace="$NAMESPACE" -o=json | jq '.status' || echo "{}")
  failure=$(echo $deployer_status | jq '.failed')
  if [[ "$failure" -gt "0" ]]; then
    clean_and_exit "ERROR Deployer failed"
  fi

  success=$(echo $deployer_status | jq '.succeeded')
  if [[ "$success" -gt "0" ]]; then
    echo "INFO Deployer job succeeded"
    break
  fi

  elapsed_time=$(( $(date +%s) - $start_time ))
  printf "Elapsed ${elapsed_time}s\r"
  if [[ "$elapsed_time" -gt "$wait_timeout" ]]; then
    clean_and_exit "ERROR Deployer job timeout"
  fi

  sleep "$poll_interval"
done

# Get the logs from the deployer before deleting the application. Set deployer name to empty so clean up doesn't try to get its logs again.
kubectl logs "jobs/$deployer_name" --namespace="$NAMESPACE" || echo "ERROR Failed to get logs for deployer $deployer_name"
deployer_name=""

echo "INFO Stop the application"
kubectl delete "application/$NAME" \
    --namespace="$NAMESPACE" \
  || clean_and_exit "ERROR Failed to stop application"

deletion_timeout=180
echo "INFO Wait for the applications to be deleted"
/scripts/wait_for_deletion.sh \
  --namespace="$NAMESPACE" \
  --kind=applications \
  --timeout="$deletion_timeout" \
  || clean_and_exit "ERROR Some applications where not deleted"

echo "INFO Wait for standard resources were deleted."
/scripts/wait_for_deletion.sh \
  --namespace="$NAMESPACE" \
  --kind=all \
  --timeout="$deletion_timeout" \
  || clean_and_exit "ERROR Some resources where not deleted"

echo "INFO Wait for service accounts to be deleted."
/scripts/wait_for_deletion.sh \
  --namespace="$NAMESPACE" \
  --kind=serviceaccounts,roles,rolebindings \
  --timeout="$deletion_timeout" \
  || clean_and_exit "ERROR Some service accounts or roles where not deleted"

delete_namespace
