{{- if not .Values.application_uid }}

apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: "{{ .Release.Name }}"
  namespace: "{{ .Release.Namespace }}"
spec:
  descriptor:
    description: |-
      A minimal example application.
  componentKinds:
  - group: batch/v1
    kind: Job
  - group: v1
    kind: Pod

{{- end }}
