apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
spec:
  containers:
  - name: {{ .Release.Name }}
    image: busybox
    command: ['sleep', '3600']
